object Versions {

    const val androidMaterialVersion="1.10.0"
    const val composeBomVersion="2023.10.01"
    const val coreKtxVersion="1.12.0"
    const val kotlin_version = "1.9.0"
    const val coroutines_version = "1.7.1"
    const val nav_version = "2.3.5"
    const val material_version = "1.3.0"
    const val hiltVersion = "2.48.1"
    const val either_version = "3.0.0"
    const val glide_version = "4.12.0"
    const val retrofitVersion = "2.9.0"
    const val billing_version = "3.0.3"
    const val work_version = "2.5.0"
    const val permissions_dispatcher = "4.8.0"
    const val firebase_ui = "7.1.1"
    const val agp_version = "8.1.2"
    const val composeVersion = "1.8.1"
    const val logginInterceptorVersion = "4.9.0"
    const val lifecycleKtxVersion = "2.6.2"
    const val appCompact = "1.3.0"
    const val hiltNavigationComposeVersion = "1.1.0"
    const val navigationComposeVersion = "2.7.5"
    const val junitJupiterVersion = "5.10.0"
    const val assertkVersion = "0.27.0"
    const val mockitoKotlinVersion = "3.2.0"
    const val kotlinxCoroutinesTestVersion = "1.6.1"
    const val turbineVersion = "1.0.0"
    const val javapoetVersion = "1.13.0"
    const val kotlinCompilerExtensionVersion = "1.5.2"
}